language: php

php:
  - 5.5

env:
  - TRANSPORT=jackrabbit
  - TRANSPORT=doctrine-dbal DB=sqlite
  - TRANSPORT=doctrine-dbal DB=mysql
  - TRANSPORT=doctrine-dbal DB=pgsql

before_script:
  - echo "memory_limit = 2048M" >> travis.php.ini
  - phpenv config-add travis.php.ini
  - composer self-update
  - composer require jackalope/jackalope-$TRANSPORT:~1.0  --prefer-source
  - cp cli-config.php.dist cli-config.php
  - sed -i 's/some-transport/$TRANSPORT/g' cli-config.php; fi
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database phpcr_benchmark;"; fi
  - if [[ "$DB" == "mysql" ]]; then sed -i 's/pdo_sqlite/pdo_mysql/g' cli-config.php; fi
  - if [[ "$DB" == "pgsql" ]]; then psql -c "create database phpcr_benchmark;" -U postgres; fi
  - if [[ "$DB" == "pgsql" ]]; then sed -i 's/pdo_sqlite/pdo_pgsql/g' cli-config.php; fi
  - if [[ "$DB" == "pgsql" ]]; then sed -i 's/root/postgres/g' cli-config.php; fi
  - if [[ "$TRANSPORT" == "doctrine-dbal" ]]; then ./vendor/bin/jackalope jackalope:init:dbal; fi
  - if [[ "$TRANSPORT" == "jackrabbit" ]]; then ./vendor/bin/jackrabbit.sh; fi

script:
  - php index.php benchmark --count 1000 --sections 100
  - php index.php benchmark --count 1000 --sections 100 --append
